version: "3.9"  # optional since v1.27.0
services:
  rabbitmq:
    container_name: go_learn_rabbitmq
    image: wisesight/rabbitmq:3.7
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

  mongodb:
    container_name: go_learn_mongodb
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=golearn
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"