version: "3.9"  # optional since v1.27.0
services:
  rabbitmq:
    container_name: go_learn_rabbitmq
    image: wisesight/rabbitmq:3.7
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

  mongodb:
    container_name: go_learn_mongodb
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=golearn
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

  elasticsearch:
    container_name: go_learn_elasticsearch
    build:
      context: .
      dockerfile: ./elasticsearch.Dockerfile
    ports:
      - 9200:9200
    volumes:
      - ./docker/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

  sense:
    container_name: go_learn_sense
    image: wisesight/sense
    ports:
      - 8888:80
    restart: "always"